name: flutter_bloc_base_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Make phone call or open web
  url_launcher:

  #iOS UIs
  cupertino_icons: ^1.0.0

  #Reactive-Dart
  rxdart: ^0.26.0

  #Business Logic Component
  flutter_bloc: ^7.0.0

  #Compare Objects
  equatable: ^2.0.0

  #Web-view
  webview_flutter:

  #Json supporter
  json_annotation: ^4.0.1

  #Network
  http: ^0.13.1
  meta: ^1.3.0
  http_parser: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  #Json supporter
  json_serializable: ^4.1.0
  build_runner: ^1.12.2

  #Save data locally in the device
  shared_preferences: ^2.0.5

flutter:
  uses-material-design: true

